//Survivor
//A+ 2014

import java.io.*;
import java.util.*;
import static java.lang.System.*;

public class survivor
{ 
	public static void gen(char[][]g1,char[][]g2,int R, int C)
	{
		int count=0;
		if(g1[R-1][C-1]=='*') count++;
		if(g1[R-1][C]=='*') count++;
		if(g1[R-1][C+1]=='*') count++;
		if(g1[R][C-1]=='*') count++;
		if(g1[R][C+1]=='*') count++;
		if(g1[R+1][C-1]=='*') count++;
		if(g1[R+1][C]=='*') count++;
		if(g1[R+1][C+1]=='*') count++;
		//organism with 2 or three neighbors survives
		if(g1[R][C]=='*'&& (count==2||count==3)) g2[R][C]='*';
		//empty cell that has 3 neighbors becomes birth cell
		if(g1[R][C]=='.'&& count==3) g2[R][C]='*';
		//organism with 4 or more neighbors, or less than 2 neighbors, dies
		if(g1[R][C]=='*'&& (count<2||count>=4)) g2[R][C]='.';
	}
	public static void main(String [] args) throws FileNotFoundException 
	{
		Scanner f = new Scanner(new File("survivor.dat"));
		int N = f.nextInt();
		f.nextLine();
		while(N-->0)
		{
			char[][]grid1 = new char[10][10];
			char[][]grid2 = new char[10][10];
			for(int x=0;x<grid1.length;x++)
			{
				Arrays.fill(grid1[x],'.');
				Arrays.fill(grid2[x],'.');
			}
			String s = f.nextLine();
			Scanner ff = new Scanner(s);
			int n = ff.nextInt();
			while(ff.hasNext())
				grid1[ff.nextInt()][ff.nextInt()]='*';
//output initial board
		out.println("GENERATION ZERO");
			for(int r = 1;r<9;r++)
			{
				for(int c=1;c<9;c++)
					out.print(grid1[r][c]);
				out.println();
			}
			out.println();	

//repeat five times
for(int z=1;z<=5;z++)
{

//process generation
			for(int r = 1;r<9;r++)
			{
				for(int c=1;c<9;c++)
					gen(grid1,grid2,r,c);
			}
//update grid1
			for(int r = 1;r<9;r++)
			{
				for(int c=1;c<9;c++)
					grid1[r][c]=grid2[r][c];
			}
//clear grid2 for next time
			for(int x=0;x<grid2.length;x++)
			{
				Arrays.fill(grid2[x],'.');
			}

//output board
			if(z==1||z==5)
			{
			out.println("GENERATION "+z);
			for(int r = 1;r<9;r++)
			{
				for(int c=1;c<9;c++)
					out.print(grid1[r][c]);
				out.println();
			}
			out.println();	
			}
		}
	}
	}
}
/*
Test Input File – survivor.dat
4 
4 4 4 4 5 4 6 4 7
8 1 1 2 2 3 3 4 4 5 4 6 3 7 2 8 1
5 4 2 4 3 4 4 4 5 4 6
16 1 4 1 7 1 8 2 7 2 8 2 2 3 2 4 2 5 2 4 4 4 5 4 6 6 5 6 6 6 7 6 8

Test Output To Screen
GENERATION ZERO
........
........
........
...****.
........
........
........
........

GENERATION 1
........
........
....**..
....**..
....**..
........
........
........

GENERATION 5
........
........
....**..
...*..*.
....**..
........
........
........

GENERATION ZERO
*.......
.*......
..*.....
...*....
...*....
..*.....
.*......
*.......

GENERATION 1
........
.*......
..*.....
..**....
..**....
..*.....
.*......
........

GENERATION 5
........
.**.....
..*.....
........
........
..*.....
.**.....
........

GENERATION ZERO
........
........
........
.*****..
........
........
........
........

GENERATION 1
........
........
..***...
..***...
..***...
........
........
........

GENERATION 5
...*....
..***...
.*.*.*..
***.***.
.*.*.*..
..***...
...*....
........

GENERATION ZERO
...*..**
.*....**
.*......
.*.***..
.*......
....****
........
........

GENERATION 1
......**
..*...**
**..***.
**..*...
..**....
.....**.
.....**.
........

GENERATION 5
........
.*...**.
**..*.*.
*.....*.
*...**..
.*.*....
..*.....
........

*/